# Práctica 05. Análisis de Datos Exploratorio con Python y Jupiter Notebook

**Programa de Estudios:** Ingeniería en Desarrollo y Gestón de Software \
**Asignatura:** Extracción de Conocimiento en Bases de Datos \
**Docente:** M.T.I Marco A. Ramírez Hernández \
**Periodo:** Mayo - Agosto 23026

### Unidad 2: Preparación de los Datos

**Nombre del Estudiante:** Ángel de Jesús Rufino Mendoza \
**Matrícula:** 230499 \
**Grado y Grupo:** 9° B IDGS

El estudiante practicará como realizar un analasis exploratorio de datos (EDA), utilizando el lenguaje de
programación de Python, y librerias comunes para la carga, manipulación, análisis y visualización prevla de un
conjunto de datos (Dataset), para esta práctica se utilizarán las librerlas de:
    
-Pandas
-Numpy
-Seaborn
-Matplotlib

1. Importar las librerias necesarlas para realizar el EDA
Comenzamos por importar la libreria que nos permitirá manipula los datos del dataset extraidos de una fuente de
datos (datasource)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

2. Creamos un DataFrame, leyendo el archivo delimitado por comas (.CSV)

In [5]:
pokemons= pd.read_csv('./Pokemon.csv')
pokemonsE= pd.read_csv('./Pokemon_Evolution_Stages.csv')

3. Imprimimos el resultado de la lectura
Este comando imprime en una tabla las columnas y las filas del dataframe, siempre de manera estándar nos mostrara
los primeros 5 y los últimos 5 registros del dataframe.

In [24]:
pokemons

,#,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,3,Venusaur,Grass,525,80,82,83,100,100,80,1,False
4,3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
800,719,Diancie,Rock,600,50,100,150,100,150,50,6,True
801,719,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
802,720,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
803,720,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
804,721,Volcanion,Fire,600,80,110,120,130,90,70,6,True

4.Obtener una muestra aleatoria de registros de dataframe usando el metodo .sample Como parametro de entrada podemos definir un entero que determina el tamaño de la muestra

In [25]:
pokemonsE

,#,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Evolution
0,1.0,Bulbasaur,Grass,318.0,45.0,49.0,49.0,65.0,65.0,45.0,1.0,False,1
1,2.0,Ivysaur,Grass,405.0,60.0,62.0,63.0,80.0,80.0,60.0,1.0,False,2
2,3.0,Venusaur,Grass,525.0,80.0,82.0,83.0,100.0,100.0,80.0,1.0,False,3
3,3.0,Venusaur,Grass,525.0,80.0,82.0,83.0,100.0,100.0,80.0,1.0,False,3
4,3.0,VenusaurMega Venusaur,Grass,625.0,80.0,100.0,123.0,122.0,120.0,80.0,1.0,False,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
806,723.0,Voltraptor,Artificial,550.0,75.0,120.0,70.0,95.0,70.0,120.0,7.0,False,1
807,724.0,Ferrogon,Artificial,600.0,95.0,135.0,120.0,75.0,95.0,80.0,7.0,False,1
808,725.0,Abyssphinx,Artificial,600.0,100.0,90.0,90.0,140.0,120.0,60.0,7.0,True,1
809,725.0,Chronarios,Artificial,700.0,110.0,130.0,110.0,130.0,110.0,110.0,7.0,True,1
810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [8]:
pokemons.sample(7) ##Obtiene una muestra de 7 pokemones aleatorios

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
69,62,Poliwrath,Water,Fighting,510,90,95,95,70,90,70,1,False
58,52,Meowth,Normal,NaN,290,40,45,35,40,40,90,1,False
698,632,Durant,Bug,Steel,484,58,109,112,48,48,109,5,False
209,192,Sunflora,Grass,NaN,425,75,75,55,105,85,30,2,False
458,410,Shieldon,Rock,Steel,350,30,42,118,42,88,30,4,False
587,523,Zebstrika,Electric,NaN,497,75,100,63,80,63,116,5,False
93,84,Doduo,Normal,Flying,310,35,85,45,35,35,75,1,False

Ejercicio 1 Muestra 50 datos

In [9]:
pokemons.sample(50)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
13,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
644,578,Duosion,Psychic,NaN,370,65,40,50,125,60,30,5,False
341,310,ManectricMega Manectric,Electric,NaN,575,70,75,80,135,80,135,3,False
688,622,Golett,Ground,Ghost,303,59,74,50,35,50,35,5,False
209,192,Sunflora,Grass,NaN,425,75,75,55,105,85,30,2,False
125,115,Kangaskhan,Normal,NaN,490,105,95,80,40,80,90,1,False
38,32,Nidoran♂,Poison,NaN,273,46,57,40,40,40,50,1,False
556,492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
440,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False
21,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
141,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
92,83,Farfetch'd,Normal,Flying,352,52,65,55,58,62,60,1,False
88,80,Slowbro,Water,Psychic,490,95,75,110,100,80,30,1,False
42,36,Clefable,Fairy,NaN,483,95,70,73,95,90,60,1,False
394,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
255,234,Stantler,Normal,NaN,465,73,95,62,85,65,85,2,False
522,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
9,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
724,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
652,586,Sawsbuck,Normal,Grass,475,80,100,70,60,70,95,5,False
587,523,Zebstrika,Electric,NaN,497,75,100,63,80,63,116,5,False
412,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
590,526,Gigalith,Rock,NaN,515,85,135,130,60,80,25,5,False
282,258,Mudkip,Water,NaN,310,50,70,50,50,50,40,3,False
85,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
485,433,Chingling,Psychic,NaN,285,45,30,50,65,50,45,4,False
169,153,Bayleef,Grass,NaN,405,60,62,80,63,80,60,2,False
259,238,Smoochum,Ice,Psychic,305,45,30,15,85,65,65,2,False
158,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
781,706,Goodra,Dragon,NaN,600,90,100,70,110,150,80,6,False
791,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
4,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
520,465,Tangrowth,Grass,NaN,535,100,100,125,110,50,50,4,False
562,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
586,522,Blitzle,Electric,NaN,295,45,60,32,50,32,76,5,False
492,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
213,196,Espeon,Psychic,NaN,525,65,65,60,130,95,110,2,False
596,531,AudinoMega Audino,Normal,Fairy,545,103,60,126,80,126,50,5,False
689,623,Golurk,Ground,Ghost,483,89,124,80,55,80,55,5,False
600,535,Tympole,Water,NaN,294,50,50,40,50,40,64,5,False
231,212,ScizorMega Scizor,Bug,Steel,600,70,150,140,65,100,75,2,False
436,388,Grotle,Grass,NaN,405,75,89,85,55,65,36,4,False
170,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
295,270,Lotad,Water,Grass,220,40,30,30,40,50,30,3,False
139,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
803,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
769,694,Helioptile,Electric,Normal,289,44,38,33,61,43,70,6,False
470,420,Cherubi,Grass,NaN,275,45,35,45,62,53,35,4,False
510,456,Finneon,Water,NaN,330,49,49,56,49,61,66,4,False
337,308,Medicham,Fighting,Psychic,410,60,60,75,60,75,80,3,False

5. Obtener una muestra de rangos definidos usando .iloc

In [10]:
pokemons_100_to_200 = pokemons.iloc[100:200]
pokemons_100_to_200

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
100,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
101,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False
102,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
103,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
104,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,179,Mareep,Electric,NaN,280,55,40,40,65,45,35,2,False
196,180,Flaaffy,Electric,NaN,365,70,55,55,80,60,45,2,False
197,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
198,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
199,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False

6. Como saber las columnas o atributos que tiene el Dataframe

In [11]:
pokemons.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

| Campo | Descripcion |
| :--- | :--- |
| **#** | El ID o número de identificación del Pokémon. |
| **Name** | El nombre del Pokémon. |
| **Type 1** | Se refiere a las propiedades elementales (tipos) asociadas tanto al Pokémon como a sus movimientos. |
| **Type 2** | Los Pokémon pueden tener hasta dos tipos (Pokémon de tipo Dual); los movimientos solo pueden tener uno. |
| **Total** | Representa la suma de todos los stats, lo que te da una idea de qué tan "pesado" o fuerte es el Pokémon. |
| **HP** | (Puntos de Salud) Es qué tanto aguante tiene un Pokémon antes de que lo dejen fuera de combate (se desmaye). |
| **Attack** | La fuerza de los ataques físicos del Pokémon. |
| **Defense** | Qué tanto aguante tiene el Pokémon contra los ataques físicos del rival. |
| **Evolution_Level** | Nivel de Evolución del Pokémon o requisitos para su cambio. |
| **Sp. Atk** | Ataque Especial; el poder de los movimientos especiales del Pokémon. |
| **Sp. Def** | Defensa Especial; qué tan resistente es el Pokémon ante los ataques especiales. |
| **Speed** | Velocidad; el Pokémon que tenga más velocidad es el que ataca primero. |
| **Generation** | Generación; Se refiere a la generación de la serie de juegos a la que pertenece. |
| **Legendary** | Indica si el Pokémon es Legendario o no (son bichos muy raros y poderosos). Es un valor booleano. |

In [7]:
pokemonsE.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Evolution'],
      dtype='object')

| Campo | Descripcion |
| :--- | :--- |
| **#** | El ID o número de identificación del Pokémon. |
| **Name** | El nombre del Pokémon. |
| **Type 1** | Se refiere a las propiedades elementales (tipos) asociadas tanto al Pokémon como a sus movimientos. |
| **Type 2** | Los Pokémon pueden tener hasta dos tipos (Pokémon de tipo Dual); los movimientos solo pueden tener uno. |
| **Total** | Representa la suma de todos los stats, lo que te da una idea de qué tan "pesado" o fuerte es el Pokémon. |
| **HP** | (Puntos de Salud) Es qué tanto aguante tiene un Pokémon antes de que lo dejen fuera de combate (se desmaye). |
| **Attack** | La fuerza de los ataques físicos del Pokémon. |
| **Defense** | Qué tanto aguante tiene el Pokémon contra los ataques físicos del rival. |
| **Evolution_Level** | Nivel de Evolución del Pokémon o requisitos para su cambio. |
| **Sp. Atk** | Ataque Especial; el poder de los movimientos especiales del Pokémon. |
| **Sp. Def** | Defensa Especial; qué tan resistente es el Pokémon ante los ataques especiales. |
| **Speed** | Velocidad; el Pokémon que tenga más velocidad es el que ataca primero. |
| **Generation** | Generación; Se refiere a la generación de la serie de juegos a la que pertenece. |
| **Legendary** | Indica si el Pokémon es Legendario o no (son bichos muy raros y poderosos). Es un valor booleano. |
| **Evolution** | Indica la fase o etapa evolutiva en la que el Pokémon se encuentra. |

7. Explorar la composición y ausencia de datos (METADATA) con .info

La libreria de pandas, incluye un método que nos permite evaluar el tipo de dato y su composición y ausencia.

In [12]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805 entries, 0 to 804
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           805 non-null    int64
 1   Name        805 non-null    object
 2   Type 1      805 non-null    object
 3   Type 2      416 non-null    object
 4   Total       805 non-null    int64
 5   HP          805 non-null    int64
 6   Attack      805 non-null    int64
 7   Defense     805 non-null    int64
 8   Sp. Atk     805 non-null    int64
 9   Sp. Def     805 non-null    int64
 10  Speed       805 non-null    int64
 11  Generation  805 non-null    int64
 12  Legendary   805 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 76.4+ KB

In [9]:
pokemonsE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811 entries, 0 to 810
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           810 non-null    float64
 1   Name        810 non-null    object
 2   Type 1      810 non-null    object
 3   Type 2      416 non-null    object
 4   Total       810 non-null    float64
 5   HP          810 non-null    float64
 6   Attack      810 non-null    float64
 7   Defense     810 non-null    float64
 8   Sp. Atk     810 non-null    float64
 9   Sp. Def     810 non-null    float64
 10  Speed       810 non-null    float64
 11  Generation  810 non-null    float64
 12  Legendary   810 non-null    object
 13  Evolution   811 non-null    int64
dtypes: float64(9), int64(1), object(4)
memory usage: 88.8+ KB

8. Limpieza de Datos.

Dependiendo del objeto del análisis algunas columnas o registro no serán necesarias en nuestro Dataframe, en este caso omitiremos los datos vacios, por los que eliminaremos la columna 'Type 2', y renombraremos la columna 'Type 1' por 'Type'.

In [8]:
pokemonsE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811 entries, 0 to 810
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           810 non-null    float64
 1   Name        810 non-null    object
 2   Type 1      810 non-null    object
 3   Type 2      416 non-null    object
 4   Total       810 non-null    float64
 5   HP          810 non-null    float64
 6   Attack      810 non-null    float64
 7   Defense     810 non-null    float64
 8   Sp. Atk     810 non-null    float64
 9   Sp. Def     810 non-null    float64
 10  Speed       810 non-null    float64
 11  Generation  810 non-null    float64
 12  Legendary   810 non-null    object
 13  Evolution   811 non-null    int64
dtypes: float64(9), int64(1), object(4)
memory usage: 88.8+ KB

In [13]:
del pokemons['Type 2']
pokemons.rename(columns={'Type 1':'Type'}, inplace= True)

In [13]:
del pokemonsE['Type 2']
pokemonsE.rename(columns={'Type 1':'Type'}, inplace= True)

Ejercicio 02: Consulta la Metadata de la actualizacion y compara los cambios con la anterior

In [15]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805 entries, 0 to 804
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           805 non-null    int64
 1   Name        805 non-null    object
 2   Type        805 non-null    object
 3   Total       805 non-null    int64
 4   HP          805 non-null    int64
 5   Attack      805 non-null    int64
 6   Defense     805 non-null    int64
 7   Sp. Atk     805 non-null    int64
 8   Sp. Def     805 non-null    int64
 9   Speed       805 non-null    int64
 10  Generation  805 non-null    int64
 11  Legendary   805 non-null    bool
dtypes: bool(1), int64(9), object(2)
memory usage: 70.1+ KB

Respuesta - Ejercicio 2:
Al comparar la metadata actual con la anterior, se observan estos cambios principales:

1. La columna "Type 2" desapareció por completo, reduciendo el número total de columnas.
2. La columna "Type 1" se renombró y ahora aparece simplemente como "Type".
3. Se eliminó la mayor fuente de datos nulos, ya que "Type 2" tenía muchos espacios vacíos.
4. El uso de memoria (memory usage) disminuyó ligeramente al quitar una columna entera.

In [14]:
pokemonsE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811 entries, 0 to 810
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           810 non-null    float64
 1   Name        810 non-null    object
 2   Type        810 non-null    object
 3   Total       810 non-null    float64
 4   HP          810 non-null    float64
 5   Attack      810 non-null    float64
 6   Defense     810 non-null    float64
 7   Sp. Atk     810 non-null    float64
 8   Sp. Def     810 non-null    float64
 9   Speed       810 non-null    float64
 10  Generation  810 non-null    float64
 11  Legendary   810 non-null    object
 12  Evolution   811 non-null    int64
dtypes: float64(9), int64(1), object(3)
memory usage: 82.5+ KB

9. Visualización de los primeros datos usando el método .head

In [17]:
pokemons.head()

,#,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,525,80,82,83,100,100,80,1,False
3,3,Venusaur,Grass,525,80,82,83,100,100,80,1,False
4,3,VenusaurMega Venusaur,Grass,625,80,100,123,122,120,80,1,False

Ejercicio 03: Muestra los últimos 10 registros del DataFrame

In [18]:
pokemons.tail(10)

,#,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,714,Noibat,Flying,245,40,30,35,45,40,55,6,False
796,715,Noivern,Flying,535,85,70,80,97,80,123,6,False
797,716,Xerneas,Fairy,680,126,131,95,131,98,99,6,True
798,717,Yveltal,Dark,680,126,131,95,131,98,99,6,True
799,718,Zygarde50% Forme,Dragon,600,108,100,121,81,95,95,6,True
800,719,Diancie,Rock,600,50,100,150,100,150,50,6,True
801,719,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
802,720,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
803,720,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
804,721,Volcanion,Fire,600,80,110,120,130,90,70,6,True

10. Estadistica básica del Dataframe 
    Pandas permite emitir un reporte de estadistica básica (medidas de tendencia) sobre datos cualitativos usando el comando .describe

In [16]:
pokemons.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,805.000000,805.000000,805.000000,805.000000,805.000000,805.000000,805.000000,805.000000,805.000000
mean,362.214907,435.362733,69.351553,79.075776,73.844720,72.829814,71.967702,68.293168,3.319255
std,208.416447,119.985831,25.510351,32.520456,31.131673,32.643439,27.794716,29.046600,1.660543
min,1.000000,180.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.000000
25%,184.000000,330.000000,50.000000,55.000000,50.000000,50.000000,50.000000,45.000000,2.000000
50%,364.000000,450.000000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.000000
75%,538.000000,515.000000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.000000
max,721.000000,780.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.000000

In [15]:
pokemonsE.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Evolution
count,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,811.000000
mean,364.446914,436.379012,69.491358,79.254321,73.975309,73.077778,72.146914,68.433333,3.341975,1.680641
std,209.695088,120.385437,25.513380,32.566023,31.111377,32.749680,27.835725,29.060716,1.680350,0.799912
min,1.000000,180.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.000000,1.000000
25%,185.250000,330.000000,50.000000,55.000000,50.000000,50.000000,50.000000,45.000000,2.000000,1.000000
50%,366.500000,450.000000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.000000,1.000000
75%,541.750000,515.000000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.000000,2.000000
max,725.000000,780.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,7.000000,4.000000

11. Calcular el total de datos no duplicados(único)

Usaremos **.len()** como función para calcular la longitud del dataframe y **.unique()** para excluir los duplicados
    
***Nota:*** No considerar ID como un atributo de llave primaria, sino el total de columnas como un solo elemento u objeto.

Obteniendo los valores unicos por columna en este caso en la columna "Name"

In [19]:
len(pokemons.Name.unique())

800

Obteniendo el total de objetos (conjunto de atributos, estrictamente iguales) únicos

In [20]:
total_unicos = len(pokemons.drop_duplicates())
total_unicos

802

Ejercicio 04: Obtener el total de IDs únicos en el dataset

In [31]:
# Opción directa y limpia
pokemons['#'].nunique()

721

Ejercicio 05: Obtener el total de tipos únicos de pokemones

In [30]:
pokemons['Type 1'].nunique()

18